name: Security Scans

on: [push, pull_request]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        if: exists('package.json')
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for Node.js
        if: exists('package.json')
        run: npm install

      - name: Set up Python
        if: exists('requirements.txt')
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies for Python
        if: exists('requirements.txt')
        run: pip install -r requirements.txt

      - name: Set up Java
        if: exists('pom.xml')
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install dependencies for Java
        if: exists('pom.xml')
        run: mvn install

      - name: Set up Ruby
        if: exists('Gemfile')
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install dependencies for Ruby
        if: exists('Gemfile')
        run: bundle install

      - name: Set up PHP
        if: exists('composer.json')
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies for PHP
        if: exists('composer.json')
        run: composer install

      - name: Debug Information
        run: |
          echo "Node.js version:"
          node --version || echo "Node.js not installed"
          echo "NPM version:"
          npm --version || echo "NPM not installed"
          echo "Python version:"
          python --version || echo "Python not installed"
          echo "Maven version:"
          mvn --version || echo "Maven not installed"
          echo "Ruby version:"
          ruby --version || echo "Ruby not installed"
          echo "PHP version:"
          php --version || echo "PHP not installed"

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/setup@v2
        with:
          token: ${{ secrets.SNYK_TOKEN }}

      - name: Test code with Snyk
        run: snyk test

      - name: Monitor code with Snyk
        run: snyk monitor

  snyk_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        if: exists('package.json')
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Snyk Code to check for code issues
        uses: snyk/actions/setup@v2
        with:
          token: ${{ secrets.SNYK_TOKEN }}

      - name: Test code with Snyk Code
        run: snyk code test

  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config=p/ci
