name: Dependency and Source Code Scanning

on: [push, pull_request]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Use the latest stable version of checkout action

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Use the latest version of setup-node action
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Snyk Dependency Scan
        uses: snyk/actions/node@v2  # Update to the correct version of Snyk action
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Use the latest stable version of checkout action

      - name: Set up Python
        uses: actions/setup-python@v4  # Use the latest version of setup-python action
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config=auto .
