name: CI

on: [push, pull_request]

jobs:
  sca_and_sast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run Snyk for SCA
    - name: Snyk SCA scan
      uses: snyk/actions/node@master
      with:
        args: monitor
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    # Run Semgrep for SAST
    - name: Semgrep SAST scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: 'auto'
