name: Semgrep Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python 3.9 and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install -y python3.9 python3-pip

      - name: Install Semgrep
        run: |
          python3.9 -m pip install semgrep --break-system-packages

      - name: Verify Semgrep installation
        run: |
          semgrep --version

      - name: Run Semgrep analysis
        run: |
          semgrep --config=policies/semgrep.yml .

      # Additional steps for your pipeline can be added here
