name: Semgrep Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install semgrep
        run: |
          # Install semgrep using the official installation script
          curl -L https://semgrep.dev/install.sh | sh -s -- -c stable

      - name: Run semgrep with API token
        env:
          SEMGREP_API_TOKEN: ${{ secrets.SEMGREP_API_TOKEN }}
        run: |
          # Set up semgrep with API token
          echo "token: $SEMGREP_API_TOKEN" > ~/.semgrep.yml
          
          # Run semgrep on your codebase
          semgrep --config=p/r/python3 --json .

      # Add more steps as needed for your workflow
